# Multi-Chain Blockchain Analytics Configuration

# Multi-Chain Configuration
chains:
  # GraphLinq Chain (Local)
  glq:
    name: "GraphLinq Chain"
    chain_id: 614
    rpc_url: "http://localhost:8545"
    ws_url: "ws://localhost:8545"
    network_type: "mainnet"
    provider: "local"
    enabled: true
    
  # Ethereum Mainnet (Infura)
  ethereum:
    name: "Ethereum Mainnet"
    chain_id: 1
    rpc_url: "https://mainnet.infura.io/v3/{INFURA_PROJECT_ID}"
    ws_url: "wss://mainnet.infura.io/ws/v3/{INFURA_PROJECT_ID}"
    network_type: "mainnet"
    provider: "infura"
    enabled: true
    
  # Polygon Mainnet (Infura)
  polygon:
    name: "Polygon Mainnet"
    chain_id: 137
    rpc_url: "https://polygon-mainnet.infura.io/v3/{INFURA_PROJECT_ID}"
    ws_url: "wss://polygon-mainnet.infura.io/ws/v3/{INFURA_PROJECT_ID}"
    network_type: "mainnet"
    provider: "infura"
    enabled: true
    
  # Base Mainnet (Infura)
  base:
    name: "Base Mainnet"
    chain_id: 8453
    rpc_url: "https://base-mainnet.infura.io/v3/{INFURA_PROJECT_ID}"
    ws_url: "wss://base-mainnet.infura.io/ws/v3/{INFURA_PROJECT_ID}"
    network_type: "mainnet"
    provider: "infura"
    enabled: true
    
  # Avalanche C-Chain Mainnet (Infura)
  avalanche:
    name: "Avalanche C-Chain"
    chain_id: 43114
    rpc_url: "https://avalanche-mainnet.infura.io/v3/{INFURA_PROJECT_ID}"
    ws_url: "wss://avalanche-mainnet.infura.io/ws/v3/{INFURA_PROJECT_ID}"
    network_type: "mainnet"
    provider: "infura"
    enabled: true
    
  # BSC Mainnet (Infura)
  bsc:
    name: "BNB Smart Chain"
    chain_id: 56
    rpc_url: "https://bsc-mainnet.infura.io/v3/{INFURA_PROJECT_ID}"
    ws_url: "wss://bsc-mainnet.infura.io/ws/v3/{INFURA_PROJECT_ID}"
    network_type: "mainnet"
    provider: "infura"
    enabled: true

# Legacy blockchain config (for backwards compatibility)
blockchain:
  name: "GraphLinq Chain"
  chain_id: 614
  rpc_url: "http://localhost:8545"
  ws_url: "ws://localhost:8545"
  network_type: "mainnet"
  
# InfluxDB Configuration
influxdb:
  url: "http://localhost:8086"
  org: "glq-analytics"
  bucket: "blockchain_data"
  # Token will be loaded from environment variable INFLUX_TOKEN

# Processing Configuration
processing:
  # Historical data processing
  batch_size: 1000  # blocks per batch
  max_workers: 8    # parallel workers
  start_block: 0
  end_block: "latest"
  
  # Real-time processing
  real_time_enabled: true
  poll_interval: 2  # seconds
  confirmation_blocks: 2  # wait for confirmations
  
  # Data extraction settings
  extract_transaction_traces: true
  extract_internal_transactions: true
  extract_logs: true
  extract_contract_code: true
  
# Analytics Configuration
analytics:
  # Master enable/disable
  enabled: true
  
  # Real-time analytics settings
  realtime:
    enabled: true
    max_processing_time: 5.0  # seconds per block
    skip_on_timeout: true     # skip analytics if processing takes too long
    
  # Module-specific controls
  modules:
    token_analytics:
      enabled: true
      track_erc20_transfers: true
      track_erc721_transfers: true
      track_erc1155_transfers: true
      min_transfer_value: 0   # minimum value to track
      
    dex_analytics:
      enabled: true
      track_swaps: true
      track_liquidity_changes: true
      min_swap_value: 0       # minimum swap value to track
      supported_protocols: ["uniswap_v2", "uniswap_v3"]
      
    defi_analytics:
      enabled: true
      track_lending: true
      track_yield_farming: true
      track_staking: true
      min_position_value: 0   # minimum position size to track
      
    advanced_analytics:
      enabled: true
      wallet_clustering: true
      contract_popularity: true
      cross_protocol_analysis: true
      
  # Performance settings
  performance:
    batch_size: 100          # events per batch
    max_memory_per_block: "50MB"
    enable_parallel_processing: true
    
  # Basic metrics (legacy compatibility)
  calculate_block_times: true
  calculate_gas_analytics: true
  calculate_transaction_fees: true
  
  # Wallet analytics
  enable_wallet_clustering: true
  min_transaction_count: 10  # for clustering
  
  # Contract analytics
  track_contract_deployments: true
  analyze_contract_interactions: true
  calculate_contract_popularity: true

# Known Contract Addresses (to be populated with GLQ chain specifics)
contracts:
  # DEX Routers
  dex_routers: []
  
  # Token Contracts
  major_tokens: []
  
  # DeFi Protocols
  lending_protocols: []
  staking_contracts: []

# Logging Configuration
logging:
  level: "INFO"
  file: "logs/blockchain_analytics.log"
  max_size: "100MB"
  backup_count: 5
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# Performance Settings
performance:
  # Connection pooling
  max_connections: 20
  connection_timeout: 30
  
  # Memory management
  max_memory_usage: "4GB"
  gc_threshold: 1000000  # records
  
  # Caching
  enable_caching: true
  cache_ttl: 3600  # seconds
  max_cache_size: 10000

# Data Retention
retention:
  # InfluxDB retention policies
  raw_data_retention: "1y"      # Keep raw data for 1 year
  analytics_retention: "5y"     # Keep analytics for 5 years
  realtime_retention: "30d"     # Keep real-time data for 30 days
  
# Monitoring and Alerting
monitoring:
  enable_metrics: true
  metrics_port: 8000
  
  # Health checks
  health_check_interval: 60  # seconds
  
  # Alerts (placeholder for future implementation)
  alerts:
    block_processing_lag_threshold: 10  # blocks
    error_rate_threshold: 0.05  # 5%